package com.pha.likaijie.bean


data class PrescMainBean(
    val ID: String?,
    val age: String?,
    val durationDesc: String?,
    val decoctDesc: String?,
    val detailNum: String?,
    val direction: String?,
    val distributeFlag: Boolean?,
    val doctor: String?,
    val eachDose: String?,
    val freq: String?,
    val gender: String?,
    val herbDiagnose: String?,
    val instruction: String?,
    val label: String?,
    val outFlag: String?,
    val patLocDesc: String?,
    val wardLocDR: String?,
    val patName: String?,
    val patNo: String?,
    val phone: String?,
    val prescNo: String?,
    val prescType: String?,
    val prescWeight: String?,
    val printDate: String?,
    val printTime: String?,
    val pyName: String?,
    val rows: List<PrescDetailBean?>?,
    val singleWeight: String?,
    val startDate: String?,
    val startTime: String?,
    val type: String?,
    val westernDiagnose: String?,
    val status: String?,
    val arcDesc: String?,
    val dispID: String?,
    val priceFinishFlag: Boolean?,
    val finishFlag: Boolean?,
    var selected: Boolean?,
    var out: Boolean?,
    var req: String? /* 退药申请单ID */
)
data class PrescDetailBean(
    val ID: String?,
    val type: String?,
    val remark: String?,
    val inci: String?,
    val inciDesc: String?,
    val priceFlag: Boolean?,
    val qty: String?,
    val qtyUom: String?,
    val singleQty: String?,
    val tipsFlag: Boolean?,
    var pyFlag: Boolean?,
    val spec: String?
)